/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dcf2b7f8-b9ff-45fb-a608-cc22304b428e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_nJZjyOXmb",
    "aws_user_pools_web_client_id": "2nkjdetvm667amed9rr65hnuee",
    "oauth": {},
    "aws_user_files_s3_bucket": "animalcrossingbuddymedias3001202423-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
